name: Update Changelog

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  update-changelog:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests pypandoc
          sudo apt-get install -y pandoc

      - name: Generate Changelog
        id: changelog
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          python scripts/update_changelog.py > CHANGELOG.md || exit 1 # Exit if script fails due to rate limit

      - name: Convert Markdown to RTF
        run: |
          python scripts/convert_md_to_rtf.py CHANGELOG.md CHANGELOG.rtf

      - name: Commit RTF Changelog
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add CHANGELOG.rtf
          git commit -m "Update changelog"
          git push
